fullnameOverride: crestem-ong

image:
  repository: code4romania/website-factory
  tag: 1.10.5

ingress:
  enabled: true
  annotations:
    "cert-manager.io/cluster-issuer": letsencrypt
  hosts:
    - host: crestem.ong
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: web-ssl
      hosts:
        - crestem.ong

resources:
  requests:
    cpu: 10m
    memory: 100M
  limits:
    cpu: 500m
    memory: 256M

env:
  - name: APP_DEBUG
    value: "false"
  - name: APP_NAME
    value: "CrestemOng"
  - name: APP_KEY
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: APP_KEY
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: DB_HOST
  - name: DB_DATABASE
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: DB_DATABASE
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: DB_PASSWORD
  - name: MAIL_HOST
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: MAIL_HOST
  - name: MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: MAIL_USERNAME
  - name: MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: MAIL_PASSWORD
  - name: MAIL_FROM_ADDRESS
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: MAIL_FROM_ADDRESS
  - name: MAIL_FROM_NAME
    value: "CrestemOng"
  - name: FILESYSTEM_DRIVER
    value: "s3"
  - name: FILESYSTEM_CLOUD
    value: "s3"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: AWS_DEFAULT_REGION
  - name: AWS_BUCKET
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: AWS_BUCKET
  - name: AWS_BUCKET_ROOT
    valueFrom:
      secretKeyRef:
        name: crestem-ong-secret
        key: AWS_BUCKET_ROOT
