fullnameOverride: esense-website

image:
  repository: code4romania/website-factory
  tag: 1.11.3

ingress:
  enabled: true
  annotations:
    "cert-manager.io/cluster-issuer": letsencrypt
    "nginx.ingress.kubernetes.io/from-to-www-redirect": "true"
  hosts:
    - host: esense.ro
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: web-ssl
      hosts:
        - esense.ro
        - www.esense.ro

resources:
  requests:
    cpu: 10m
    memory: 70Mi
  limits:
    cpu: 250m
    memory: 456Mi

env:
  - name: WEBSITE_FACTORY_EDITION
    value: "ong"
  - name: APP_URL
    value: "https://www.esense.ro"
  - name: APP_KEY
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: APP_KEY
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: DB_HOST
  - name: DB_DATABASE
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: DB_DATABASE
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: DB_USERNAME
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: DB_PASSWORD
  - name: MAIL_HOST
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: MAIL_HOST
  - name: MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: MAIL_USERNAME
  - name: MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: MAIL_PASSWORD
  - name: MAIL_FROM_ADDRESS
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: MAIL_FROM_ADDRESS
  - name: FILESYSTEM_DRIVER
    value: "s3"
  - name: FILESYSTEM_CLOUD
    value: "s3"
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: AWS_ACCESS_KEY_ID
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: AWS_SECRET_ACCESS_KEY
  - name: AWS_DEFAULT_REGION
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: AWS_DEFAULT_REGION
  - name: AWS_BUCKET
    valueFrom:
      secretKeyRef:
        name: esense-secret
        key: AWS_BUCKET
