fullnameOverride: un-acoperis

image:
  repository: code4romania/un-acoperis
  tag: v1.18

ingress:
  enabled: true
  annotations:
    "cert-manager.io/cluster-issuer": letsencrypt
    "nginx.ingress.kubernetes.io/from-to-www-redirect": "true"
  hosts:
    - host: unacoperis.ro
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: web-ssl
      hosts:
        - unacoperis.ro

resources:
  requests:
    cpu: 10m
    memory: 170Mi
  limits:
    cpu: 600m
    memory: 2Gi

env:
  - name: APP_NAME
    value: "Un Acoperiș"
  - name: APP_ENV
    value: production
  - name: APP_DEBUG
    value: "false"
  - name: ADMIN_APP_URL
    value: unacoperis.ro/cms
  - name: ADMIN_APP_PATH
    value: /
  - name: APP_URL
    value: "http://unacoperis.ro"
  - name: LOG_CHANNEL
    value: stderr
  - name: DB_CONNECTION
    value: mysql
  - name: DB_PORT
    value: "3306"
  - name: BROADCAST_DRIVER
    value: log
  - name: CACHE_DRIVER
    value: file
  - name: QUEUE_CONNECTION
    value: sync
  - name: SESSION_DRIVER
    value: database
  - name: SESSION_LIFETIME
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: session_lifetime
  - name: MAIL_MAILER
    value: smtp
  - name: MAIL_PORT
    value: "2587"
  - name: MAIL_ENCRYPTION
    value: tls
  - name: MAIL_FROM_NAME
    value: "Un Acoperiș"
  - name: MAIL_TO_CONTACT_ADDRESS
    value: dopomoha@code4.ro
  - name: MAIL_TO_HELP_ADDRESS
    value: dopomoha@code4.ro
  - name: MAIL_FROM_ADDRESS
    value: admin@unacoperis.ro
  - name: AWS_DEFAULT_REGION
    value: eu-west-1
  - name: SCOUT_DRIVER
    value: database
  - name: AWS_BUCKET
    value: un-acoperis
  - name: AWS_CDN_URL
    value: http://taskforce-unacoperis.s3-website-eu-west-1.amazonaws.com
  - name: AWS_PUBLIC_BUCKET
    value: taskforce-unacoperis
  - name: AWS_PRIVATE_BUCKET
    value: taskforce-unacoperis-private
  - name: APP_KEY
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: app_key
  - name: DB_HOST
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: database_host
  - name: DB_DATABASE
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: database_name
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: database_username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: database_password
  - name: MAIL_HOST
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: mail_host
  - name: MAIL_USERNAME
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: mail_username
  - name: MAIL_PASSWORD
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: mail_password
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: aws_access_key_id
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: aws_access_secret_key
  - name: NOCAPTCHA_SECRET
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: nocaptcha_secret
  - name: NOCAPTCHA_SITEKEY
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: nocaptcha_sitekey
  - name: SENTRY_LARAVEL_DSN
    valueFrom:
      secretKeyRef:
        name: un-acoperis-secret
        key: sentry_laravel
