apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: date-la-zi-admin
  namespace: date-la-zi-admin
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: code4romania/admin-la-zi:v1.7
          resources:
            limits:
              cpu: 200m
              memory: 310M
          ports:
            - containerPort: 80
          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: app_key
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: db_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: db_password
            - name: SENTRY_LARAVEL_DSN
              value: "https://910c909d82b441fca86c8d540ef40b6f@o375441.ingest.sentry.io/6219339"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: aws_secret_access_key
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"
            - name: AWS_CLOUDFRONT_DISTRIBUTION_ID
              valueFrom:
                secretKeyRef:
                  name: date-la-zi-admin-secret
                  key: aws_cloudfront_distr_id
            - name: PARSE_TIME_LIMIT
              value: "180"
