apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rezultate-vot
  namespace: rezultate-vot
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containers:
        - image: code4romania/rezultate-vot-api:v1.0
          resources:
            requests:
              cpu: 100m
              memory: 240M
            limits:
              cpu: 1
              memory: 1Gi
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: rezultate-vot-secret
                  key: db_connection
            - name: ASPNETCORE__ENVIRONMENT
              value: "Production"
            - name: S3Bucket__BucketName
              value: "rezultatevot-images-upload"
            - name: S3Bucket__AccessKeyId
              value: "AKIASQDJNISKZBUCKRGI"
            - name: S3Bucket__AccessKeySecret
              valueFrom:
                secretKeyRef:
                  name: rezultate-vot-secret
                  key: s3_secret_access_key
            - name: ScheduleTaskEnabled
              value: "false"
            - name: LiveElectionSettings__ResultsTypes
              value: "part"
            - name: LiveElectionSettings__FtpUser
              valueFrom:
                secretKeyRef:
                  name: rezultate-vot-secret
                  key: liveelectionsettings_ftp_user
            - name: LiveElectionSettings__FtpPassword
              valueFrom:
                secretKeyRef:
                  name: rezultate-vot-secret
                  key: liveelectionsettings_ftp_password
            - name: LiveElectionSettings__TurnoutUrl
              value: "https://prezenta.roaep.ro/parlamentare06122020/data/csv/simpv/presence_now.csv"
            - name: LiveElectionSettings__TurnoutIntervalInMinutes
              value: "1"
            - name: LiveElectionSettings__ResultsUrl
              value: "https://prezenta.roaep.ro/parlamentare06122020/data/csv/sicpv/"
            - name: LiveElectionSettings__ResultsCacheInMinutes
              value: "1"
            - name: LiveElectionSettings__CsvCacheInMinutes
              value: "3"
