fullnameOverride: rezultate-vot

image:
  repository: code4romania/rezultate-vot-api
  tag: v1.0

ingress:
  enabled: true
  annotations:
    "cert-manager.io/cluster-issuer": letsencrypt
  hosts:
    - host: api.rezultatevot.ro
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: web-ssl
      hosts:
        - api.rezultatevot.ro

resources:
  requests:
    cpu: 50m
    memory: 300M
  limits:
    cpu: 500m
    memory: 500M

env:
  - name: ConnectionStrings__DefaultConnection
    valueFrom:
      secretKeyRef:
        name: rezultate-vot-secret
        key: db_connection
  - name: ASPNETCORE__ENVIRONMENT
    value: "Production"
  - name: S3Bucket__BucketName
    value: "rezultatevot-images-upload"
  - name: S3Bucket__AccessKeyId
    value: "AKIASQDJNISKZBUCKRGI"
  - name: S3Bucket__AccessKeySecret
    valueFrom:
      secretKeyRef:
        name: rezultate-vot-secret
        key: s3_secret_access_key
  - name: ScheduleTaskEnabled
    value: "false"
  - name: LiveElectionSettings__ResultsTypes
    value: "part"
  - name: LiveElectionSettings__FtpUser
    valueFrom:
      secretKeyRef:
        name: rezultate-vot-secret
        key: liveelectionsettings_ftp_user
  - name: LiveElectionSettings__FtpPassword
    valueFrom:
      secretKeyRef:
        name: rezultate-vot-secret
        key: liveelectionsettings_ftp_password
  - name: LiveElectionSettings__TurnoutUrl
    value: "https://prezenta.roaep.ro/parlamentare06122020/data/csv/simpv/presence_now.csv"
  - name: LiveElectionSettings__TurnoutIntervalInMinutes
    value: "1"
  - name: LiveElectionSettings__ResultsUrl
    value: "https://prezenta.roaep.ro/parlamentare06122020/data/csv/sicpv/"
  - name: LiveElectionSettings__ResultsCacheInMinutes
    value: "1"
  - name: LiveElectionSettings__CsvCacheInMinutes
    value: "3"
