apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: acasainsiguranta
  namespace: acasainsiguranta
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "1"
    spec:
      containers:
        - image: code4romania/website-factory:1.7.3
          resources:
            requests:
              cpu: 10m
              memory: 100M
            limits:
              cpu: 200m
              memory: 256M
          ports:
            - containerPort: 80
          env:
            - name: WEBSITE_FACTORY_EDITION
              value: "internal"
            - name: WEBSITE_FACTORY_HIDE_BANNER
              value: "false"
            - name: APP_URL
              value: "https://acasainsiguranta.ro"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: APP_KEY
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: DB_HOST
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: DB_DATABASE
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: DB_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: MAIL_HOST
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: MAIL_PASSWORD
            - name: MAIL_FROM_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: MAIL_FROM_ADDRESS
            - name: FILESYSTEM_DRIVER
              value: "s3"
            - name: FILESYSTEM_CLOUD
              value: "s3"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: AWS_DEFAULT_REGION
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: acasainsiguranta-secret
                  key: AWS_BUCKET
