apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ec-contest
  namespace: ec-contest
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/max-scale: "3"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: code4romania/ec-contest:v1.1
          resources:
            limits:
              cpu: 200m
              memory: 250M 
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              php artisan migrate --force &&
              exec /usr/sbin/apache2ctl -D FOREGROUND
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: "Laravel"
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: "false"
            - name: APP_URL
              value: "https://api-euroquiz.heroesof.tech"
            - name: LOG_CHANNEL
              value: stderr
            - name: DB_CONNECTION
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: BROADCAST_DRIVER
              value: log
            - name: CACHE_DRIVER
              value: file
            - name: QUEUE_CONNECTION
              value: sync
            - name: SESSION_DRIVER
              value: database
            - name: SESSION_LIFETIME
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: session_lifetime
            - name: MAIL_MAILER
              value: smtp
            - name: MAIL_PORT
              value: "2587"
            - name: MAIL_ENCRYPTION
              value: tls
            - name: MAIL_FROM_NAME
              value: "Euroquiz"
            - name: MAIL_FROM_ADDRESS
              value: concurs@bseurope.com
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: app_key
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: database_host
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: database_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: database_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: database_password
            - name: MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: mail_host
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: mail_username
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ec-contest-secret
                  key: mail_password

