apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: infra
  sources:
    - chart: ingress-nginx
      helm:
        valueFiles:
          - $myRepo/infra/ingress-nginx/values.yaml
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.13.1
    - repoURL: https://github.com/code4romania/code4ro-k8s.git
      targetRevision: HEAD
      ref: myRepo
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
